spring:
  application:
    name: user_service
  datasource:
    username: postgres
    password: 8472
    url: jdbc:postgresql://localhost:5432/kafka-example
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO

server:
  port: 8000

kafka:
  host: localhost:9092
  topics:
    user-created:
      topicName: ${spring.application.name}.user_created.0
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000